services:
  - type: web
    name: devr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dev_r.wsgi
    postDeployCommand: |
    python manage.py collectstatic --noinput 
    python manage.py migrate

